services:
  database:
    container_name: django_mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  # backend:
  #   container_name: django_backend
  #   build: backend/
  #   env_file:
  #     - backend/.env 
    